apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio.fullname" . }}
  namespace: {{ .Values.nameSpace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
      protocol: TCP
      name: portfolio
  selector:
    {{- include "portfolio.selectorLabels" . | nindent 4 }}
