# Default values for bolcategory.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/jiffysaas1/bolcategory
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "JARVIS-MAIN-vendorcategorisation_2930Mar21"
  env:
  - name: PYTHONIOENCODING
    value: "UTF-8"
  - name: PATH
    value: "/root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  - name: LANG
    value: "C.UTF-8"
  - name: GPG_KEY
    value: "E3FF2839C048B25C084DEBE9B26995E310250568"
  - name: PYTHON_VERSION
    value: 3.8.8
  - name: PYTHON_PIP_VERSION
    value: 21.0.1
  - name: PYTHON_GET_PIP_URL
    value: "https://github.com/pypa/get-pip/raw/b60e2320d9e8d02348525bd74e871e466afdf77c/get-pip.py"
  - name: PYTHON_GET_PIP_SHA256
    value: "c3b81e5d06371e135fb3156dc7d8fd6270735088428c4a9a5ec1f342e2024565"
  - name: PYTHONPATH
    value: ":/mllib"
  - name: DEBIAN_FRONTEND
    value: "noninteractive"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: "NodePort"
  port: 8654

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
      - path: /
        backend:
          serviceName: chart-example.local
          servicePort: 8654
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

nameSpace: default
