---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-nginx-configmap
data:
  invoiceml.conf: |-
    upstream invoiceml_server {
      #server unix://var/tmp/supervisor.sock fail_timeout=0;
    
      # For a TCP configuration:
      server invoiceml:8651 fail_timeout=0;
    }
    upstream invoicecategory_server {
      #server unix://var/tmp/supervisor.sock fail_timeout=0;
        
      # For a TCP configuration:
      server invoicecategory:8652 fail_timeout=0;
    }
    upstream bolml_server {
      #server unix://var/tmp/supervisor.sock fail_timeout=0;
      
      # For a TCP configuration:
      server bolml:8653 fail_timeout=0;
    }
    upstream handwriting_server {
      #server unix://var/tmp/supervisor.sock fail_timeout=0;

      # For a TCP configuration:
      server hwsegmentation:8567 fail_timeout=0;
    }
    server {
      listen 8765 default;
      server_name  _;
      tcp_nopush on;
      tcp_nodelay on;
      server_tokens off;

      # ssl on;
      # ssl_certificate /etc/nginx/ssl/cert.pem;
      # ssl_certificate_key /etc/nginx/ssl/key.pem;
      ssl_protocols TLSv1.2;
      ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

      gzip  on;
      gzip_http_version 1.1;
      gzip_vary on;
      gzip_comp_level 6;
      gzip_proxied any;
      gzip_types text/plain text/html text/css application/json application/javascript application/x-javascript text/javascript text/xml application/xml application/rss+xml application/atom+xml application/rdf+xml;

      # make sure gzip does not lose large gzipped js or css files
      # see http://blog.leetsoft.com/2007/07/25/nginx-gzip-ssl.html
      gzip_buffers 16 8k;

      # Disable gzip for certain browsers.
      gzip_disable “MSIE [1-6].(?!.*SV1)”;

      keepalive_timeout 0;
      underscores_in_headers   on;
      client_max_body_size 10m;

      #access_log  /var/log/jiffy/jiffy.access.log;
      access_log  /var/log/nginx/invoiceml.access.log;

      location /api/invoice/ml/swagger/ {
        proxy_redirect      off;
        proxy_set_header    Host                    $host:$server_port;
        proxy_set_header    X-Real-IP               $remote_addr;
        proxy_set_header    X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Protocol    $scheme;
        proxy_pass          http://invoiceml_server/api/;
        proxy_connect_timeout 300s;
        proxy_read_timeout    300s;
      }
      location /api/invoice/ml/hello/ {
        proxy_redirect      off;
        proxy_set_header    Host                    $host:$server_port;
        proxy_set_header    X-Real-IP               $remote_addr;
        proxy_set_header    X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Protocol    $scheme;
        proxy_pass          http://invoiceml_server/api/hello/;
        proxy_connect_timeout 300s;
        proxy_read_timeout    300s;
      }
      location /api/invoice/ml/version/ {
        proxy_redirect      off;
        proxy_set_header    Host                    $host:$server_port;
        proxy_set_header    X-Real-IP               $remote_addr;
        proxy_set_header    X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Protocol    $scheme;
        proxy_pass          http://invoiceml_server/api/version/;
        proxy_connect_timeout 300s;
        proxy_read_timeout    300s;
      }
      location /api/invoice/ml/predict/ {
        proxy_redirect      off;
        proxy_set_header    Host                    $host:$server_port;
        proxy_set_header    X-Real-IP               $remote_addr;
        proxy_set_header    X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Protocol    $scheme;
        proxy_pass          http://invoiceml_server/api/predict/;
        proxy_connect_timeout 300s;
        proxy_read_timeout    300s;
      }
      location /api/invoice/ml/train/ {
        proxy_redirect      off;
        proxy_set_header    Host                    $host:$server_port;
        proxy_set_header    X-Real-IP               $remote_addr;
        proxy_set_header    X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Protocol    $scheme;
        proxy_pass          http://invoiceml_server/api/train/;
        proxy_connect_timeout 300s;
        proxy_read_timeout    300s;
      }
      location /api/invoice/ml/jsonconversion/ {
        proxy_redirect      off;
        proxy_set_header    Host                    $host:$server_port;
        proxy_set_header    X-Real-IP               $remote_addr;
        proxy_set_header    X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Protocol    $scheme;
        proxy_pass          http://invoiceml_server/api/jsonconversion/;
        proxy_connect_timeout 300s;
        proxy_read_timeout    300s;
      }
      location /api/invoice/ml/imagesearch/ {
        proxy_redirect      off;
        proxy_set_header    Host                    $host:$server_port;
        proxy_set_header    X-Real-IP               $remote_addr;
        proxy_set_header    X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Protocol    $scheme;
        proxy_pass          http://invoiceml_server/api/imagesearch/;
        proxy_connect_timeout 300s;
        proxy_read_timeout    300s;
      }
      location /api/invoice/ml/getdescriptor/ {
        proxy_redirect      off;
        proxy_set_header    Host                    $host:$server_port;
        proxy_set_header    X-Real-IP               $remote_addr;
        proxy_set_header    X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Protocol    $scheme;
        proxy_pass          http://invoiceml_server/api/getdescriptor/;
        proxy_connect_timeout 300s;
        proxy_read_timeout    300s;
      }
      location /api/invoice/category/swagger/ {
        proxy_redirect      off;
        proxy_set_header    Host                    $host:$server_port;
        proxy_set_header    X-Real-IP               $remote_addr;
        proxy_set_header    X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Protocol    $scheme;
        proxy_pass          http://invoicecategory_server/api/;
        proxy_connect_timeout 300s;
        proxy_read_timeout    300s;
      }
      location /api/invoice/category/predict/ {
        proxy_redirect      off;
        proxy_set_header    Host                    $host:$server_port;
        proxy_set_header    X-Real-IP               $remote_addr;
        proxy_set_header    X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Protocol    $scheme;
        proxy_pass          http://invoicecategory_server/api/predict/;
        proxy_connect_timeout 300s;
        proxy_read_timeout    300s;
      }
      location /api/invoice/category/hello/ {
        proxy_redirect      off;
        proxy_set_header    Host                    $host:$server_port;
        proxy_set_header    X-Real-IP               $remote_addr;
        proxy_set_header    X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Protocol    $scheme;
        proxy_pass          http://invoicecategory_server/api/hello/;
        proxy_connect_timeout 300s;
        proxy_read_timeout    300s;
      }
      location /api/invoice/category/version/ {
        proxy_redirect      off;
        proxy_set_header    Host                    $host:$server_port;
        proxy_set_header    X-Real-IP               $remote_addr;
        proxy_set_header    X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Protocol    $scheme;
        proxy_pass          http://invoicecategory_server/api/version/;
        proxy_connect_timeout 300s;
        proxy_read_timeout    300s;
      }
      location /api/bol/ml/version/ {
        proxy_redirect      off;
        proxy_set_header    Host                    $host:$server_port;
        proxy_set_header    X-Real-IP               $remote_addr;
        proxy_set_header    X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Protocol    $scheme;
        proxy_pass          http://bolml_server/api/version/;
        proxy_connect_timeout 300s;
        proxy_read_timeout    300s;
      }
      location /api/bol/ml/swagger/ {
        proxy_redirect      off;
        proxy_set_header    Host                    $host:$server_port;
        proxy_set_header    X-Real-IP               $remote_addr;
        proxy_set_header    X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Protocol    $scheme;
        proxy_pass          http://bolml_server/api/;
        proxy_connect_timeout 300s;
        proxy_read_timeout    300s;
      }
      location /api/bol/ml/hello/ {
        proxy_redirect      off;
        proxy_set_header    Host                    $host:$server_port;
        proxy_set_header    X-Real-IP               $remote_addr;
        proxy_set_header    X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Protocol    $scheme;
        proxy_pass          http://bolml_server/api/hello/;
        proxy_connect_timeout 300s;
        proxy_read_timeout    300s;
      }
      location /api/bol/ml/predict/ {
        proxy_redirect      off;
        proxy_set_header    Host                    $host:$server_port;
        proxy_set_header    X-Real-IP               $remote_addr;
        proxy_set_header    X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Protocol    $scheme;
        proxy_pass          http://bolml_server/api/predict/;
        proxy_connect_timeout 300s;
        proxy_read_timeout    300s;
      }
      location /api/bol/ml/train/ {
        proxy_redirect      off;
        proxy_set_header    Host                    $host:$server_port;
        proxy_set_header    X-Real-IP               $remote_addr;
        proxy_set_header    X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Protocol    $scheme;
        proxy_pass          http://bolml_server/api/train/;
        proxy_connect_timeout 300s;
        proxy_read_timeout    300s;
      }
      location /api/handwriting/predict/ {
        proxy_redirect      off;
        proxy_set_header    Host                    $host:$server_port;
        proxy_set_header    X-Real-IP               $remote_addr;
        proxy_set_header    X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Protocol    $scheme;
        proxy_pass          http://handwriting_server/predict/;
        proxy_connect_timeout 300s;
        proxy_read_timeout    300s;
      }
    }

