apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    jiffy.app: {{ .Release.Name }}
spec:
  type: "NodePort"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
      name: "invoicecategory"
  selector:
    jiffy.app: {{ .Release.Name }}