apiVersion: v1
kind: Service
metadata:
  name: {{ include "result-handler.fullname" . }}
  namespace: {{ .Values.nameSpace }}
  labels:
    {{- include "result-handler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "result-handler.selectorLabels" . | nindent 4 }}
